// Generated by CoffeeScript 1.3.3
(function() {
  var arrayEqual;

  arrayEqual = function(a, b) {
    var i;
    i = Math.max(a.length, b.length, 1);
    while (i-- >= 0 && a[i] === b[i]) {
      continue;
    }
    return i === -2;
  };

  exports.flatten = function(arr) {
    var r;
    r = [];
    while (!arrayEqual(r, arr)) {
      r = arr;
      arr = [].concat.apply([], arr);
    }
    return arr;
  };

}).call(this);
