// Generated by CoffeeScript 1.3.3
(function() {

  exports.flatten = function(arr) {
    var i, len, ret;
    ret = [];
    len = arr.length;
    i = 0;
    while (i < len) {
      if (Array.isArray(arr[i])) {
        exports.flatten(arr[i], ret);
      } else {
        ret.push(arr[i]);
      }
      ++i;
    }
    return ret;
  };

}).call(this);
