// Generated by CoffeeScript 1.3.3
(function() {
  var Get, Method,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Method = require('../Method');

  module.exports = Get = (function(_super) {

    __extends(Get, _super);

    function Get() {
      return Get.__super__.constructor.apply(this, arguments);
    }

    Get.prototype.defaultVerb = function() {
      return 'get';
    };

    Get.prototype.defaultSteps = function() {
      return ['begin', 'input', 'load', 'output'];
    };

    Get.prototype.input = function(req, res, next) {
      var rest;
      rest = req.rest;
      rest._id = req.param('_id');
      return next(null);
    };

    Get.prototype.load = function(req, res, next) {
      var rest, _id;
      rest = req.rest;
      _id = rest._id;
      return rest.model.findById(_id, function(err, doc) {
        if (err) {
          return next(err);
        } else {
          rest.document = doc;
          return next(null);
        }
      });
    };

    Get.prototype.output = function(req, res, next) {
      var rest;
      rest = req.rest;
      if (!rest.document) {
        return res.send(404);
      } else {
        return res.json(rest.document.toObject());
      }
    };

    return Get;

  })(Method);

}).call(this);
