// Generated by CoffeeScript 1.3.3
(function() {
  var Method, Post,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Method = require('../Method');

  module.exports = Post = (function(_super) {

    __extends(Post, _super);

    function Post() {
      return Post.__super__.constructor.apply(this, arguments);
    }

    Post.prototype.defaultVerb = function() {
      return 'post';
    };

    Post.prototype.defaultSteps = function() {
      return ['begin', 'input', 'create', 'save', 'serialize', 'output'];
    };

    Post.prototype.input = function(req, res, next) {
      var rest;
      rest = req.rest;
      rest.fieldValues = req.body;
      return next(null);
    };

    Post.prototype.create = function(req, res, next) {
      var field, options, rest, value, _ref;
      rest = req.rest;
      options = this.options;
      rest.document = new rest.model;
      _ref = rest.fieldValues;
      for (field in _ref) {
        if (!__hasProp.call(_ref, field)) continue;
        value = _ref[field];
        rest.document[field] = value;
      }
      if (options.ctimeField) {
        rest.document[options.ctimeField] = rest.currentTime;
      }
      if (options.mtimeField) {
        rest.document[options.mtimeField] = rest.currentTime;
      }
      return next(null);
    };

    Post.prototype.save = function(req, res, next) {
      var rest;
      rest = req.rest;
      return rest.document.save(function(err) {
        if (err) {
          return next(err);
        } else {
          return next(null);
        }
      });
    };

    Post.prototype.serialize = function(req, res, next) {
      var rest;
      rest = req.rest;
      rest.result = rest.document.toObject();
      return next(null);
    };

    return Post;

  })(Method);

}).call(this);
