// Generated by CoffeeScript 1.3.3
(function() {

  module.exports = function() {
    var list;
    list = {
      load: function(req, res, next) {
        var rest;
        rest = req.rest;
        return rest.query.limit(false).skip(false).count(function(err, count) {
          if (err) {
            return next(err);
          }
          rest.meta.totalCount = count;
          return next(null);
        });
      }
    };
    return {
      list: list
    };
  };

}).call(this);
