// Generated by CoffeeScript 1.3.3
(function() {

  module.exports = function(options) {
    var ITEMS_PER_PAGE, PAGE_PARAM, list;
    options = options || {};
    ITEMS_PER_PAGE = options.itemsPerPage || 10;
    PAGE_PARAM = options.pageParameterName || 'page';
    list = {
      begin: function(req, res, next) {
        var rest;
        rest = req.rest;
        rest.pagination = {};
        return next(null);
      },
      query: function(req, res, next) {
        var limit, page, pagination, query, skip, _ref;
        _ref = req.rest, query = _ref.query, pagination = _ref.pagination;
        page = parseInt(req.param(PAGE_PARAM)) || 1;
        if (page <= 0) {
          page = 1;
        }
        pagination.currentPage = page;
        skip = ITEMS_PER_PAGE * (page - 1);
        limit = ITEMS_PER_PAGE;
        query.skip(skip);
        query.limit(limit);
        return next(null);
      },
      load: function(req, res, next) {
        var pagination, query, _ref;
        _ref = req.rest, query = _ref.query, pagination = _ref.pagination;
        return query.limit(false).skip(false).count(function(err, count) {
          if (err) {
            return next(err);
          }
          pagination.totalItems = count;
          pagination.totalPages = Math.ceil(count / ITEMS_PER_PAGE);
          return next(null);
        });
      },
      serialize: function(req, res, next) {
        var meta, pagination, _ref;
        _ref = req.rest, meta = _ref.meta, pagination = _ref.pagination;
        meta.pagination = pagination;
        return next(null);
      }
    };
    return {
      list: list
    };
  };

}).call(this);
