// Generated by CoffeeScript 1.3.3
(function() {

  module.exports = function() {
    var list;
    list = {
      query: function(req, res, next) {
        var end, start;
        start = req.param('start', 0);
        end = req.param('end', null);
        req.rest.query.skip(start);
        if (end != null) {
          req.rest.query.limit(end - start + 1);
        }
        return next(null);
      }
    };
    return {
      list: list
    };
  };

}).call(this);
